apiVersion: v1
kind: Service
metadata:
  labels:
    app: expenses
  name: expenses
  namespace: default
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: expenses
  type: ClusterIP